version: '3.9'

services:

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - backend

#  api-service:
#    container_name: api-service
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    ports:
#      - '80:8080'
#    networks:
#      - backend
#    depends_on:
#      - postgres


networks:
  backend:
    driver: bridge
