spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://api-service.local
    title: ${API_URL}
    version: 1.0.0

